### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by eblabs** [d-fofanov/xpbdUnity#1]
Hi,
Its really cool to see more people getting involved in bringing XPBD to Unity. Just curious, do you have an example scene using this?
Thanks and great work!

**Comment by d-fofanov** [comment]
Hi.
I've added a simple baloon example here https://github.com/d-fofanov/xpbdExamples
Feel free to raise issues if it doen't work properly :)

**Comment by eblabs** [comment]
Thanks so much, Ill check it out!
